export type FieldD = {
  id: number;
  name?: string;
  widget_id?: number;
  options?: any;
  required?: 1 | 0;
  validation_rules?: any;
  priority: number;
  obj?: any;
  type: LeadTypes;
  deleted_at: null;
  createdAt: any;
  updatedAt: any;
  deletedAt: null;
  value?: any;
  show?: boolean;
  complete?: boolean;
};

export const enum LeadTypes {
  email = "email",
  number = "number",
  phone = "phone",
  name = "name",

  text = "text",
  textarea = "textarea",
  select = "select",
  radio = "radio",
  checkbox = "checkbox",

  date_picker = "date_picker",
}

export const Flags = [
  {
    country_name: "Afghanistan",
    country_code: "AF",
    flag_emoji: "🇦🇫",
    dial_code: "+93",
    id: 1,
  },
  {
    country_name: "Albania",
    country_code: "AL",
    flag_emoji: "🇦🇱",
    dial_code: "+355",
    id: 2,
  },
  {
    country_name: "Algeria",
    country_code: "DZ",
    flag_emoji: "🇩🇿",
    dial_code: "+213",
    id: 3,
  },
  {
    country_name: "Andorra",
    country_code: "AD",
    flag_emoji: "🇦🇩",
    dial_code: "+376",
    id: 4,
  },
  {
    country_name: "Angola",
    country_code: "AO",
    flag_emoji: "🇦🇴",
    dial_code: "+244",
    id: 5,
  },
  {
    country_name: "Antigua and Barbuda",
    country_code: "AG",
    flag_emoji: "🇦🇬",
    dial_code: "+1",
    id: 6,
  },
  {
    country_name: "Argentina",
    country_code: "AR",
    flag_emoji: "🇦🇷",
    dial_code: "+54",
    id: 7,
  },
  {
    country_name: "Armenia",
    country_code: "AM",
    flag_emoji: "🇦🇲",
    dial_code: "+374",
    id: 8,
  },
  {
    country_name: "Australia",
    country_code: "AU",
    flag_emoji: "🇦🇺",
    dial_code: "+61",
    id: 9,
  },
  {
    country_name: "Austria",
    country_code: "AT",
    flag_emoji: "🇦🇹",
    dial_code: "+43",
    id: 10,
  },
  {
    country_name: "Azerbaijan",
    country_code: "AZ",
    flag_emoji: "🇦🇿",
    dial_code: "+994",
    id: 11,
  },
  {
    country_name: "Bahamas",
    country_code: "BS",
    dial_code: "+1-242",
    flag_emoji: "🇧🇸",
    id: 12,
  },
  {
    country_name: "Bahrain",
    country_code: "BH",
    dial_code: "+973",
    flag_emoji: "🇧🇭",
    id: 13,
  },
  {
    country_name: "Bangladesh",
    country_code: "BD",
    dial_code: "+880",
    flag_emoji: "🇧🇩",
    id: 14,
  },
  {
    country_name: "Barbados",
    country_code: "BB",
    dial_code: "+1-246",
    flag_emoji: "🇧🇧",
    id: 15,
  },
  {
    country_name: "Belarus",
    country_code: "BY",
    dial_code: "+375",
    flag_emoji: "🇧🇾",
    id: 16,
  },
  {
    country_name: "Belgium",
    country_code: "BE",
    dial_code: "+32",
    flag_emoji: "🇧🇪",
    id: 17,
  },
  {
    country_name: "Belize",
    country_code: "BZ",
    dial_code: "+501",
    flag_emoji: "🇧🇿",
    id: 18,
  },
  {
    country_name: "Bolivia",
    country_code: "BO",
    dial_code: "+591",
    flag_emoji: "🇧🇴",
    id: 19,
  },
  {
    country_name: "Bosnia and Herzegovina",
    country_code: "BA",
    dial_code: "+387",
    flag_emoji: "🇧🇦",
    id: 20,
  },
  {
    country_name: "Botswana",
    country_code: "BW",
    dial_code: "+267",
    flag_emoji: "🇧🇼",
    id: 21,
  },
  {
    country_name: "Brazil",
    country_code: "BR",
    dial_code: "+55",
    flag_emoji: "🇧🇷",
    id: 22,
  },
  {
    country_name: "Brunei",
    country_code: "BN",
    dial_code: "+673",
    flag_emoji: "🇧🇳",
    id: 23,
  },
  {
    country_name: "Bulgaria",
    country_code: "BG",
    dial_code: "+359",
    flag_emoji: "🇧🇬",
    id: 24,
  },
  {
    country_name: "Burkina Faso (Upper Volta)",
    country_code: "BF",
    dial_code: "+226",
    flag_emoji: "🇧🇫",
    id: 25,
  },
  {
    country_name: "Burma",
    country_code: "MM",
    dial_code: "+95",
    flag_emoji: "🇲🇲",
    id: 26,
  },
  {
    country_name: "Burundi",
    country_code: "BI",
    dial_code: "+257",
    flag_emoji: "🇧🇮",
    id: 27,
  },
  {
    country_name: "Cabo Verde",
    country_code: "CV",
    dial_code: "+238",
    flag_emoji: "🇨🇻",
    id: 28,
  },
  {
    country_name: "Cambodia",
    country_code: "KH",
    dial_code: "+855",
    flag_emoji: "🇰🇭",
    id: 29,
  },
  {
    country_name: "Cameroon",
    country_code: "CM",
    dial_code: "+237",
    flag_emoji: "🇨🇲",
    id: 30,
  },
  {
    country_name: "Canada",
    country_code: "CA",
    dial_code: "+1",
    flag_emoji: "🇨🇦",
    id: 31,
  },
  {
    country_name: "Cayman Islands",
    country_code: "KY",
    dial_code: "+1-345",
    flag_emoji: "🇰🇾",
    id: 32,
  },
  {
    country_name: "Central African Republic",
    country_code: "CF",
    dial_code: "+236",
    flag_emoji: "🇨🇫",
    id: 33,
  },
  {
    country_name: "Chad",
    country_code: "TD",
    dial_code: "+235",
    flag_emoji: "🇹🇩",
    id: 34,
  },
  {
    country_name: "Chile",
    country_code: "CL",
    dial_code: "+56",
    flag_emoji: "🇨🇱",
    id: 35,
  },
  {
    country_name: "China",
    country_code: "CN",
    dial_code: "+86",
    flag_emoji: "🇨🇳",
    id: 36,
  },
  {
    country_name: "Colombia",
    country_code: "CO",
    dial_code: "+57",
    flag_emoji: "🇨🇴",
    id: 37,
  },
  {
    country_name: "Comoros",
    country_code: "KM",
    dial_code: "+269",
    flag_emoji: "🇰🇲",
    id: 38,
  },
  {
    country_name: "Costa Rica",
    country_code: "CR",
    dial_code: "+506",
    flag_emoji: "🇨🇷",
    id: 39,
  },
  {
    country_name: "Cote d’Ivoire (Ivory Coast)",
    country_code: "CI",
    dial_code: "+225",
    flag_emoji: "🇨🇮",
    id: 40,
  },
  {
    country_name: "Croatia",
    country_code: "HR",
    dial_code: "+385",
    flag_emoji: "🇭🇷",
    id: 41,
  },
  {
    country_name: "Cuba",
    country_code: "CU",
    dial_code: "+53",
    flag_emoji: "🇨🇺",
    id: 42,
  },
  {
    country_name: "Cyprus",
    country_code: "CY",
    dial_code: "+357",
    flag_emoji: "🇨🇾",
    id: 43,
  },
  {
    country_name: "Czechia",
    country_code: "CZ",
    dial_code: "+420",
    flag_emoji: "🇨🇿",
    id: 44,
  },
  {
    country_name: "Democratic Republic of the Congo",
    country_code: "CD",
    dial_code: "+243",
    flag_emoji: "🇨🇩",
    id: 45,
  },
  {
    country_name: "Denmark",
    country_code: "DK",
    dial_code: "+45",
    flag_emoji: "🇩🇰",
    id: 46,
  },
  {
    country_name: "Djibouti",
    country_code: "DJ",
    dial_code: "+253",
    flag_emoji: "🇩🇯",
    id: 47,
  },
  {
    country_name: "Dominica",
    country_code: "DM",
    dial_code: "+1-767",
    flag_emoji: "🇩🇲",
    id: 48,
  },
  {
    country_name: "Dominican Republic",
    country_code: "DO",
    dial_code: "+1-809",
    flag_emoji: "🇩🇴",
    id: 49,
  },
  {
    country_name: "Dominican Republic",
    country_code: "DO",
    dial_code: "+1-829",
    flag_emoji: "🇩🇴",
    id: 50,
  },
  {
    country_name: "Dominican Republic",
    country_code: "DO",
    dial_code: "+1-849",
    flag_emoji: "🇩🇴",
    id: 51,
  },
  {
    country_name: "Ecuador",
    country_code: "EC",
    dial_code: "+593",
    flag_emoji: "🇪🇨",
    id: 52,
  },
  {
    country_name: "Egypt",
    country_code: "EG",
    dial_code: "+20",
    flag_emoji: "🇪🇬",
    id: 53,
  },
  {
    country_name: "El Salvador",
    country_code: "SV",
    dial_code: "+503",
    flag_emoji: "🇸🇻",
    id: 54,
  },
  {
    country_name: "Equatorial Guinea",
    country_code: "GQ",
    dial_code: "+240",
    flag_emoji: "🇬🇶",
    id: 55,
  },
  {
    country_name: "Eritrea",
    country_code: "ER",
    dial_code: "+291",
    flag_emoji: "🇪🇷",
    id: 56,
  },
  {
    country_name: "Estonia",
    country_code: "EE",
    dial_code: "+372",
    flag_emoji: "🇪🇪",
    id: 57,
  },
  {
    country_name: "Eswatini",
    country_code: "SZ",
    dial_code: "+268",
    flag_emoji: "🇸🇿",
    id: 58,
  },
  {
    country_name: "Ethiopia",
    country_code: "ET",
    dial_code: "+251",
    flag_emoji: "🇪🇹",
    id: 59,
  },
  {
    country_name: "Fiji",
    country_code: "FJ",
    dial_code: "+679",
    flag_emoji: "🇫🇯",
    id: 60,
  },
  {
    country_name: "Finland",
    country_code: "FI",
    dial_code: "+358",
    flag_emoji: "🇫🇮",
    id: 61,
  },
  {
    country_name: "France",
    country_code: "FR",
    dial_code: "+33",
    flag_emoji: "🇫🇷",
    id: 62,
  },
  {
    country_name: "Gabon",
    country_code: "GA",
    dial_code: "+241",
    flag_emoji: "🇬🇦",
    id: 63,
  },
  {
    country_name: "Gambia",
    country_code: "GM",
    dial_code: "+220",
    flag_emoji: "🇬🇲",
    id: 64,
  },
  {
    country_name: "Georgia",
    country_code: "GE",
    dial_code: "+995",
    flag_emoji: "🇬🇪",
    id: 65,
  },
  {
    country_name: "Germany",
    country_code: "DE",
    dial_code: "+49",
    flag_emoji: "🇩🇪",
    id: 66,
  },
  {
    country_name: "Ghana",
    country_code: "GH",
    dial_code: "+233",
    flag_emoji: "🇬🇭",
    id: 67,
  },
  {
    country_name: "Greece",
    country_code: "GR",
    dial_code: "+30",
    flag_emoji: "🇬🇷",
    id: 68,
  },
  {
    country_name: "Grenada",
    country_code: "GD",
    dial_code: "+1-473",
    flag_emoji: "🇬🇩",
    id: 69,
  },
  {
    country_name: "Guatemala",
    country_code: "GT",
    dial_code: "+502",
    flag_emoji: "🇬🇹",
    id: 70,
  },
  {
    country_name: "Guinea",
    country_code: "GN",
    dial_code: "+224",
    flag_emoji: "🇬🇳",
    id: 71,
  },
  {
    country_name: "Guinea-Bissau",
    country_code: "GW",
    dial_code: "+245",
    flag_emoji: "🇬🇼",
    id: 72,
  },
  {
    country_name: "Guyana",
    country_code: "GY",
    dial_code: "+592",
    flag_emoji: "🇬🇾",
    id: 73,
  },
  {
    country_name: "Haiti",
    country_code: "HT",
    dial_code: "+509",
    flag_emoji: "🇭🇹",
    id: 74,
  },
  {
    country_name: "Holy See",
    country_code: "VA",
    dial_code: "+379",
    flag_emoji: "🇻🇦",
    id: 75,
  },
  {
    country_name: "Honduras",
    country_code: "HN",
    dial_code: "+504",
    flag_emoji: "🇭🇳",
    id: 76,
  },
  {
    country_name: "Hungary",
    country_code: "HU",
    dial_code: "+36",
    flag_emoji: "🇭🇺",
    id: 77,
  },
  {
    country_name: "Iceland",
    country_code: "IS",
    dial_code: "+354",
    flag_emoji: "🇮🇸",
    id: 78,
  },
  {
    country_name: "India",
    country_code: "IN",
    dial_code: "+91",
    flag_emoji: "🇮🇳",
    id: 79,
  },
  {
    country_name: "Indonesia",
    country_code: "ID",
    dial_code: "+62",
    flag_emoji: "🇮🇩",
    id: 80,
  },
  {
    country_name: "Iran",
    country_code: "IR",
    dial_code: "+98",
    flag_emoji: "🇮🇷",
    id: 81,
  },
  {
    country_name: "Iraq",
    country_code: "IQ",
    dial_code: "+964",
    flag_emoji: "🇮🇶",
    id: 82,
  },
  {
    country_name: "Ireland",
    country_code: "IE",
    dial_code: "+353",
    flag_emoji: "🇮🇪",
    id: 83,
  },
  {
    country_name: "Israel",
    country_code: "IL",
    dial_code: "+972",
    flag_emoji: "🇮🇱",
    id: 84,
  },
  {
    country_name: "Italy",
    country_code: "IT",
    dial_code: "+39",
    flag_emoji: "🇮🇹",
    id: 85,
  },
  {
    country_name: "Jamaica",
    country_code: "JM",
    dial_code: "+1-876",
    flag_emoji: "🇯🇲",
    id: 86,
  },
  {
    country_name: "Japan",
    country_code: "JP",
    dial_code: "+81",
    flag_emoji: "🇯🇵",
    id: 87,
  },
  {
    country_name: "Jordan",
    country_code: "JO",
    dial_code: "+962",
    flag_emoji: "🇯🇴",
    id: 88,
  },
  {
    country_name: "Kazakhstan",
    country_code: "KZ",
    dial_code: "+7",
    flag_emoji: "🇰🇿",
    id: 89,
  },
  {
    country_name: "Kenya",
    country_code: "KE",
    dial_code: "+254",
    flag_emoji: "🇰🇪",
    id: 90,
  },
  {
    country_name: "Kiribati",
    country_code: "KI",
    dial_code: "+686",
    flag_emoji: "🇰🇮",
    id: 91,
  },
  {
    country_name: "Korea",
    country_code: "KR",
    dial_code: "+82",
    flag_emoji: "🇰🇷",
    id: 92,
  },
  {
    country_name: "Kosovo",
    country_code: "XK",
    dial_code: "+383",
    flag_emoji: "🇽🇰",
    id: 93,
  },
  {
    country_name: "Kuwait",
    country_code: "KW",
    dial_code: "+965",
    flag_emoji: "🇰🇼",
    id: 94,
  },
  {
    country_name: "Kyrgyzstan",
    country_code: "KG",
    dial_code: "+996",
    flag_emoji: "🇰🇬",
    id: 95,
  },
  {
    country_name: "Laos",
    country_code: "LA",
    dial_code: "+856",
    flag_emoji: "🇱🇦",
    id: 96,
  },
  {
    country_name: "Latvia",
    country_code: "LV",
    dial_code: "+371",
    flag_emoji: "🇱🇻",
    id: 97,
  },
  {
    country_name: "Lebanon",
    country_code: "LB",
    dial_code: "+961",
    flag_emoji: "🇱🇧",
    id: 98,
  },
  {
    country_name: "Lesotho",
    country_code: "LS",
    dial_code: "+266",
    flag_emoji: "🇱🇸",
    id: 99,
  },
  {
    country_name: "Liberia",
    country_code: "LR",
    dial_code: "+231",
    flag_emoji: "🇱🇷",
    id: 100,
  },
  {
    country_name: "Libya",
    country_code: "LY",
    dial_code: "+218",
    flag_emoji: "🇱🇾",
    id: 101,
  },
  {
    country_name: "Liechtenstein",
    country_code: "LI",
    dial_code: "+423",
    flag_emoji: "🇱🇮",
    id: 102,
  },
  {
    country_name: "Lithuania",
    country_code: "LT",
    dial_code: "+370",
    flag_emoji: "🇱🇹",
    id: 103,
  },
  {
    country_name: "Luxembourg",
    country_code: "LU",
    dial_code: "+352",
    flag_emoji: "🇱🇺",
    id: 104,
  },
  {
    country_name: "Madagascar",
    country_code: "MG",
    dial_code: "+261",
    flag_emoji: "🇲🇬",
    id: 105,
  },
  {
    country_name: "Malawi",
    country_code: "MW",
    dial_code: "+265",
    flag_emoji: "🇲🇼",
    id: 106,
  },
  {
    country_name: "Malaysia",
    country_code: "MY",
    dial_code: "+60",
    flag_emoji: "🇲🇾",
    id: 107,
  },
  {
    country_name: "Maldives",
    country_code: "MV",
    dial_code: "+960",
    flag_emoji: "🇲🇻",
    id: 108,
  },
  {
    country_name: "Mali",
    country_code: "ML",
    dial_code: "+223",
    flag_emoji: "🇲🇱",
    id: 109,
  },
  {
    country_name: "Malta",
    country_code: "MT",
    dial_code: "+356",
    flag_emoji: "🇲🇹",
    id: 110,
  },
  {
    country_name: "Marshall Islands",
    country_code: "MH",
    dial_code: "+692",
    flag_emoji: "🇲🇭",
    id: 111,
  },
  {
    country_name: "Mauritania",
    country_code: "MR",
    dial_code: "+222",
    flag_emoji: "🇲🇷",
    id: 112,
  },
  {
    country_name: "Mauritius",
    country_code: "MU",
    dial_code: "+230",
    flag_emoji: "🇲🇺",
    id: 113,
  },
  {
    country_name: "Mexico",
    country_code: "MX",
    dial_code: "+52",
    flag_emoji: "🇲🇽",
    id: 114,
  },
  {
    country_name: "Micronesia",
    country_code: "FM",
    dial_code: "+691",
    flag_emoji: "🇫🇲",
    id: 115,
  },
  {
    country_name: "Moldova",
    country_code: "MD",
    dial_code: "+373",
    flag_emoji: "🇲🇩",
    id: 116,
  },
  {
    country_name: "Monaco",
    country_code: "MC",
    dial_code: "+377",
    flag_emoji: "🇲🇨",
    id: 117,
  },
  {
    country_name: "Mongolia",
    country_code: "MN",
    dial_code: "+976",
    flag_emoji: "🇲🇳",
    id: 118,
  },
  {
    country_name: "Montenegro",
    country_code: "ME",
    dial_code: "+382",
    flag_emoji: "🇲🇪",
    id: 119,
  },
  {
    country_name: "Morocco",
    country_code: "MA",
    dial_code: "+212",
    flag_emoji: "🇲🇦",
    id: 120,
  },
  {
    country_name: "Mozambique",
    country_code: "MZ",
    dial_code: "+258",
    flag_emoji: "🇲🇿",
    id: 121,
  },
  {
    country_name: "Namibia",
    country_code: "NA",
    dial_code: "+264",
    flag_emoji: "🇳🇦",
    id: 122,
  },
  {
    country_name: "Nauru",
    country_code: "NR",
    dial_code: "+674",
    flag_emoji: "🇳🇷",
    id: 123,
  },
  {
    country_name: "Nepal",
    country_code: "NP",
    dial_code: "+977",
    flag_emoji: "🇳🇵",
    id: 124,
  },
  {
    country_name: "Netherlands",
    country_code: "NL",
    dial_code: "+31",
    flag_emoji: "🇳🇱",
    id: 125,
  },
  {
    country_name: "New Zealand",
    country_code: "NZ",
    dial_code: "+64",
    flag_emoji: "🇳🇿",
    id: 126,
  },
  {
    country_name: "Nicaragua",
    country_code: "NI",
    dial_code: "+505",
    flag_emoji: "🇳🇮",
    id: 127,
  },
  {
    country_name: "Niger",
    country_code: "NE",
    dial_code: "+227",
    flag_emoji: "🇳🇪",
    id: 128,
  },
  {
    country_name: "Nigeria",
    country_code: "NG",
    dial_code: "+234",
    flag_emoji: "🇳🇬",
    id: 129,
  },
  {
    country_name: "North Macedonia",
    country_code: "MK",
    dial_code: "+389",
    flag_emoji: "🇲🇰",
    id: 130,
  },
  {
    country_name: "Norway",
    country_code: "NO",
    dial_code: "+47",
    flag_emoji: "🇳🇴",
    id: 131,
  },
  {
    country_name: "Oman",
    country_code: "OM",
    dial_code: "+968",
    flag_emoji: "🇴🇲",
    id: 132,
  },
  {
    country_name: "Pakistan",
    country_code: "PK",
    dial_code: "+92",
    flag_emoji: "🇵🇰",
    id: 133,
  },
  {
    country_name: "Palau",
    country_code: "PW",
    dial_code: "+680",
    flag_emoji: "🇵🇼",
    id: 134,
  },
  {
    country_name: "Panama",
    country_code: "PA",
    dial_code: "+507",
    flag_emoji: "🇵🇦",
    id: 135,
  },
  {
    country_name: "Papua New Guinea",
    country_code: "PG",
    dial_code: "+675",
    flag_emoji: "🇵🇬",
    id: 136,
  },
  {
    country_name: "Paraguay",
    country_code: "PY",
    dial_code: "+595",
    flag_emoji: "🇵🇾",
    id: 137,
  },
  {
    country_name: "Peru",
    country_code: "PE",
    dial_code: "+51",
    flag_emoji: "🇵🇪",
    id: 138,
  },
  {
    country_name: "Philippines",
    country_code: "PH",
    dial_code: "+63",
    flag_emoji: "🇵🇭",
    id: 139,
  },
  {
    country_name: "Poland",
    country_code: "PL",
    dial_code: "+48",
    flag_emoji: "🇵🇱",
    id: 140,
  },
  {
    country_name: "Portugal",
    country_code: "PT",
    dial_code: "+351",
    flag_emoji: "🇵🇹",
    id: 141,
  },
  {
    country_name: "Qatar",
    country_code: "QA",
    dial_code: "+974",
    flag_emoji: "🇶🇦",
    id: 142,
  },
  {
    country_name: "Republic of Korea (South Korea)",
    country_code: "KR",
    dial_code: "+82",
    flag_emoji: "🇰🇷",
    id: 143,
  },
  {
    country_name: "Republic of the Congo",
    country_code: "CG",
    dial_code: "+242",
    flag_emoji: "🇨🇬",
    id: 144,
  },
  {
    country_name: "Romania",
    country_code: "RO",
    dial_code: "+40",
    flag_emoji: "🇷🇴",
    id: 145,
  },
  {
    country_name: "Russia",
    country_code: "RU",
    dial_code: "+7",
    flag_emoji: "🇷🇺",
    id: 146,
  },
  {
    country_name: "Rwanda",
    country_code: "RW",
    dial_code: "+250",
    flag_emoji: "🇷🇼",
    id: 147,
  },
  {
    country_name: "Saint Kitts and Nevis",
    country_code: "KN",
    dial_code: "+1-869",
    flag_emoji: "🇰🇳",
    id: 148,
  },
  {
    country_name: "Saint Lucia",
    country_code: "LC",
    dial_code: "+1-758",
    flag_emoji: "🇱🇨",
    id: 149,
  },
  {
    country_name: "Saint Vincent and the Grenadines",
    country_code: "VC",
    dial_code: "+1-784",
    flag_emoji: "🇻🇨",
    id: 150,
  },
  {
    country_name: "Samoa",
    country_code: "WS",
    dial_code: "+685",
    flag_emoji: "🇼🇸",
    id: 151,
  },
  {
    country_name: "San Marino",
    country_code: "SM",
    dial_code: "+378",
    flag_emoji: "🇸🇲",
    id: 152,
  },
  {
    country_name: "Sao Tome and Principe",
    country_code: "ST",
    dial_code: "+239",
    flag_emoji: "🇸🇹",
    id: 153,
  },
  {
    country_name: "Saudi Arabia",
    country_code: "SA",
    dial_code: "+966",
    flag_emoji: "🇸🇦",
    id: 154,
  },
  {
    country_name: "Senegal",
    country_code: "SN",
    dial_code: "+221",
    flag_emoji: "🇸🇳",
    id: 155,
  },
  {
    country_name: "Serbia",
    country_code: "RS",
    dial_code: "+381",
    flag_emoji: "🇷🇸",
    id: 156,
  },
  {
    country_name: "Seychelles",
    country_code: "SC",
    dial_code: "+248",
    flag_emoji: "🇸🇨",
    id: 157,
  },
  {
    country_name: "Sierra Leone",
    country_code: "SL",
    dial_code: "+232",
    flag_emoji: "🇸🇱",
    id: 158,
  },
  {
    country_name: "Singapore",
    country_code: "SG",
    dial_code: "+65",
    flag_emoji: "🇸🇬",
    id: 159,
  },
  {
    country_name: "Slovakia",
    country_code: "SK",
    dial_code: "+421",
    flag_emoji: "🇸🇰",
    id: 160,
  },
  {
    country_name: "Slovenia",
    country_code: "SI",
    dial_code: "+386",
    flag_emoji: "🇸🇮",
    id: 161,
  },
  {
    country_name: "Solomon Islands",
    country_code: "SB",
    dial_code: "+677",
    flag_emoji: "🇸🇧",
    id: 162,
  },
  {
    country_name: "Somalia",
    country_code: "SO",
    dial_code: "+252",
    flag_emoji: "🇸🇴",
    id: 163,
  },
  {
    country_name: "South Africa",
    country_code: "ZA",
    dial_code: "+27",
    flag_emoji: "🇿🇦",
    id: 164,
  },
  {
    country_name: "South Sudan",
    country_code: "SS",
    dial_code: "+211",
    flag_emoji: "🇸🇸",
    id: 165,
  },
  {
    country_name: "Spain",
    country_code: "ES",
    dial_code: "+34",
    flag_emoji: "🇪🇸",
    id: 166,
  },
  {
    country_name: "Sri Lanka",
    country_code: "LK",
    dial_code: "+94",
    flag_emoji: "🇱🇰",
    id: 167,
  },
  {
    country_name: "Sudan",
    country_code: "SD",
    dial_code: "+249",
    flag_emoji: "🇸🇩",
    id: 168,
  },
  {
    country_name: "Suriname",
    country_code: "SR",
    dial_code: "+597",
    flag_emoji: "🇸🇷",
    id: 169,
  },
  {
    country_name: "Sweden",
    country_code: "SE",
    dial_code: "+46",
    flag_emoji: "🇸🇪",
    id: 170,
  },
  {
    country_name: "Switzerland",
    country_code: "CH",
    dial_code: "+41",
    flag_emoji: "🇨🇭",
    id: 171,
  },
  {
    country_name: "Syria",
    country_code: "SY",
    dial_code: "+963",
    flag_emoji: "🇸🇾",
    id: 172,
  },
  {
    country_name: "Tajikistan",
    country_code: "TJ",
    dial_code: "+992",
    flag_emoji: "🇹🇯",
    id: 173,
  },
  {
    country_name: "Tanzania",
    country_code: "TZ",
    dial_code: "+255",
    flag_emoji: "🇹🇿",
    id: 174,
  },
  {
    country_name: "Thailand",
    country_code: "TH",
    dial_code: "+66",
    flag_emoji: "🇹🇭",
    id: 175,
  },
  {
    country_name: "Timor-Leste",
    country_code: "TL",
    dial_code: "+670",
    flag_emoji: "🇹🇱",
    id: 176,
  },
  {
    country_name: "Togo",
    country_code: "TG",
    dial_code: "+228",
    flag_emoji: "🇹🇬",
    id: 177,
  },
  {
    country_name: "Tonga",
    country_code: "TO",
    dial_code: "+676",
    flag_emoji: "🇹🇴",
    id: 178,
  },
  {
    country_name: "Trinidad and Tobago",
    country_code: "TT",
    dial_code: "+1-868",
    flag_emoji: "🇹🇹",
    id: 179,
  },
  {
    country_name: "Tunisia",
    country_code: "TN",
    dial_code: "+216",
    flag_emoji: "🇹🇳",
    id: 180,
  },
  {
    country_name: "Turkey",
    country_code: "TR",
    dial_code: "+90",
    flag_emoji: "🇹🇷",
    id: 181,
  },
  {
    country_name: "Turkmenistan",
    country_code: "TM",
    dial_code: "+993",
    flag_emoji: "🇹🇲",
    id: 182,
  },
  {
    country_name: "Tuvalu",
    country_code: "TV",
    dial_code: "+688",
    flag_emoji: "🇹🇻",
    id: 183,
  },
  {
    country_name: "Uganda",
    country_code: "UG",
    dial_code: "+256",
    flag_emoji: "🇺🇬",
    id: 184,
  },
  {
    country_name: "Ukraine",
    country_code: "UA",
    dial_code: "+380",
    flag_emoji: "🇺🇦",
    id: 185,
  },
  {
    country_name: "United Arab Emirates",
    country_code: "AE",
    dial_code: "+971",
    flag_emoji: "🇦🇪",
    id: 186,
  },
  {
    country_name: "United Kingdom",
    country_code: "GB",
    dial_code: "+44",
    flag_emoji: "🇬🇧",
    id: 187,
  },
  {
    country_name: "United States",
    country_code: "US",
    flag_emoji: "🇺🇸",
    dial_code: "+1",
    id: 188,
  },
  {
    country_name: "Uruguay",
    country_code: "UY",
    dial_code: "+598",
    flag_emoji: "🇺🇾",
    id: 189,
  },
  {
    country_name: "Uzbekistan",
    country_code: "UZ",
    dial_code: "+998",
    flag_emoji: "🇺🇿",
    id: 190,
  },
  {
    country_name: "Vanuatu",
    country_code: "VU",
    dial_code: "+678",
    flag_emoji: "🇻🇺",
    id: 191,
  },
  {
    country_name: "Venezuela",
    country_code: "VE",
    dial_code: "+58",
    flag_emoji: "🇻🇪",
    id: 192,
  },
  {
    country_name: "Vietnam",
    country_code: "VN",
    dial_code: "+84",
    flag_emoji: "🇻🇳",
    id: 193,
  },
  {
    country_name: "Yemen",
    country_code: "YE",
    dial_code: "+967",
    flag_emoji: "🇾🇪",
    id: 194,
  },
  {
    country_name: "Zambia",
    country_code: "ZM",
    dial_code: "+260",
    flag_emoji: "🇿🇲",
    id: 195,
  },
  {
    country_name: "Zimbabwe",
    country_code: "ZW",
    dial_code: "+263",
    flag_emoji: "🇿🇼",
    id: 196,
  },
];
