export enum LanguageCodesE {
  en = "en",
  fr = "fr",
  es = "es",
  de = "de",
  it = "it",
  pt = "pt",
  ru = "ru",
  zh = "zh",
  ja = "ja",
  ar = "ar",
  hi = "hi",
  no = "no",
  bn = "bn",
  pa = "pa",
  jv = "jv",
  ko = "ko",
  te = "te",
  mr = "mr",
  ta = "ta",
  tr = "tr",
  ur = "ur",
  vi = "vi",
  fa = "fa",
  gu = "gu",
  pl = "pl",
  uk = "uk",
  ml = "ml",
  kn = "kn",
  or = "or",
  ne = "ne",
  my = "my",
  az = "az",
  sw = "sw",
  uz = "uz",
  yo = "yo",
  am = "am",
  sd = "sd",
  ro = "ro",
  mai = "mai",
  nl = "nl",
  ha = "ha",
  el = "el",
  km = "km",
  sh = "sh",
  so = "so",
  hu = "hu",
  ceb = "ceb",
  cs = "cs",
  sv = "sv",
  da = "da",
  fi = "fi",
  sk = "sk",
  lt = "lt",
  sl = "sl",
  lv = "lv",
  et = "et",
  is = "is",
  lb = "lb",
  mt = "mt",
  gd = "gd",
  cy = "cy",
  eu = "eu",
  gl = "gl",
  ca = "ca",
  ga = "ga",
  hy = "hy",
  ka = "ka",
  ku = "ku",
  kk = "kk",
  ky = "ky",
  tg = "tg",
  tt = "tt",
  tk = "tk",
  ug = "ug",
  haw = "haw",
  mi = "mi",
  sm = "sm",
  to = "to",
  ht = "ht",
  rw = "rw",
  st = "st",
  sn = "sn",
  xh = "xh",
  zu = "zu",
  af = "af",
  sq = "sq",
  be = "be",
  bs = "bs",
  hr = "hr",
  co = "co",
  fo = "fo",
  fy = "fy",
  mg = "mg",
  mn = "mn",
  ps = "ps",
  qu = "qu",
  sc = "sc",
  he = "he",
  th = "th",
}

export const LanguageLabels: { [key in LanguageCodesE]: string } = {
  en: "English",
  fr: "French",
  es: "Spanish",
  de: "German",
  it: "Italian",
  pt: "Portuguese",
  ru: "Russian",
  zh: "Chinese",
  ja: "Japanese",
  ar: "Arabic",
  hi: "Hindi",
  no: "Norwegian",
  bn: "Bengali",
  pa: "Punjabi",
  jv: "Javanese",
  ko: "Korean",
  te: "Telugu",
  mr: "Marathi",
  ta: "Tamil",
  tr: "Turkish",
  ur: "Urdu",
  vi: "Vietnamese",
  fa: "Persian",
  gu: "Gujarati",
  pl: "Polish",
  uk: "Ukrainian",
  ml: "Malayalam",
  kn: "Kannada",
  or: "Oriya",
  ne: "Nepali",
  my: "Burmese",
  az: "Azerbaijani",
  sw: "Swahili",
  uz: "Uzbek",
  yo: "Yoruba",
  am: "Amharic",
  sd: "Sindhi",
  ro: "Romanian",
  mai: "Maithili",
  nl: "Dutch",
  ha: "Hausa",
  el: "Greek",
  km: "Khmer",
  sh: "Serbo-Croatian",
  so: "Somali",
  hu: "Hungarian",
  ceb: "Cebuano",
  cs: "Czech",
  sv: "Swedish",
  da: "Danish",
  fi: "Finnish",
  sk: "Slovak",
  lt: "Lithuanian",
  sl: "Slovenian",
  lv: "Latvian",
  et: "Estonian",
  is: "Icelandic",
  lb: "Luxembourgish",
  mt: "Maltese",
  gd: "Scottish Gaelic",
  cy: "Welsh",
  eu: "Basque",
  gl: "Galician",
  ca: "Catalan",
  ga: "Irish",
  hy: "Armenian",
  ka: "Georgian",
  ku: "Kurdish",
  kk: "Kazakh",
  ky: "Kyrgyz",
  tg: "Tajik",
  tt: "Tatar",
  tk: "Turkmen",
  ug: "Uyghur",
  haw: "Hawaiian",
  mi: "Maori",
  sm: "Samoan",
  to: "Tongan",
  ht: "Haitian Creole",
  rw: "Kinyarwanda",
  st: "Sesotho",
  sn: "Shona",
  xh: "Xhosa",
  zu: "Zulu",
  af: "Afrikaans",
  sq: "Albanian",
  be: "Belarusian",
  bs: "Bosnian",
  hr: "Croatian",
  co: "Corsican",
  fo: "Faroese",
  fy: "Frisian",
  mg: "Malagasy",
  mn: "Mongolian",
  ps: "Pashto",
  qu: "Quechua",
  sc: "Sardinian",
  he: "Hebrew",
  th: "Thai",
  // Note: Adjusted Cantonese to use "zh" and merged with Chinese.
};
